apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: msa-project
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE account_db;
    CREATE DATABASE transaction_db;
    GRANT ALL PRIVILEGES ON DATABASE auth_db TO "user";
    GRANT ALL PRIVILEGES ON DATABASE account_db TO "user";
    GRANT ALL PRIVILEGES ON DATABASE transaction_db TO "user";
