apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: msa-project
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE order_db;
    CREATE DATABASE payment_db;
    GRANT ALL PRIVILEGES ON DATABASE auth_db TO "user";
    GRANT ALL PRIVILEGES ON DATABASE order_db TO "user";
    GRANT ALL PRIVILEGES ON DATABASE payment_db TO "user";
